### ISSUE TITLE
AtomFeedSupport cause error with `_model: none` pages

### ISSUE THREAD

**Issue by item4** [lektor/lektor-website#12] opened 2015-12-22 12:46 UTC
* `/content/test.xml/contents.lr`
```
_template: test.html
---
_model: none
```

* `/models/none.ini`
→ empty

* `template/test.html`
```html
hello world
```

* parts or loooong log
```
Webpack build finished
U index.html
U feed.xml
  E feed.xml (RuntimeError: Body field not found: 'body')
U page/2/index.html
U feed.xml
  E feed.xml (RuntimeError: Body field not found: 'body')
U page/3/index.html
U feed.xml
  E feed.xml (RuntimeError: Body field not found: 'body')
U page/4/index.html
U feed.xml
  E feed.xml (RuntimeError: Body field not found: 'body')
U 2015-12-21/Hello_Website/index.html
U feed.xml
  E feed.xml (RuntimeError: Body field not found: 'body')
U 2015-12-21/Hello_Website1/index.html
U feed.xml
  E feed.xml (RuntimeError: Body field not found: 'body')
U 2015-12-21/Hello_Website3/index.html
U feed.xml
  E feed.xml (RuntimeError: Body field not found: 'body')
U temp-test.xml
```

cause `(RuntimeError: Body field not found: 'body')`

**Comment by item4** [comment] 2015-12-22 12:55
installed package: all in this repo

**Comment by mitsuhiko** [comment] 2015-12-23 15:24
Closing this here. This is not a bug in the plugin and you already opened up an issue in the main lektor repo for the actual underlying issue.

**Closed by mitsuhiko** 2015-12-23 15:24 UTC
