### ISSUE TITLE
Atom plugin page is out of date

### ISSUE THREAD

**Issue by dwt** [lektor/lektor-website#335] opened 2022-02-19 11:44 UTC
The atom plugin 0.4.0 was released some time ago, but the plugin page still points to version 0.3.1, which doesn't work with the current lektor release.

Just took me some time to figure this problem out - and I guess this will just take a rebuild of the website.

Is there some automation that needs regular kicking? I wold be glad to help get a GitHub action going that nightly builds the website if that is what is required.

**Comment by yagebu** [comment] 2022-02-20 14:39
Closing this as a duplicate of #330

**Closed by yagebu** 2022-02-20 14:39 UTC
