### ISSUE TITLE
bad url link

### ISSUE THREAD

**Issue by alan-cugler** [lektor/lektor-website#201] opened 2018-05-09 03:00 UTC
From this website url :https://www.getlektor.com/docs/api/db/obj/ the link "Assets" at the beginning of the second bullet point leads to this dead link : https://www.getlektor.com/docs/api/db/asset/

**Comment by nixjdm** [comment] 2018-05-14 04:42
Closing as dupe of #90

**Closed by nixjdm** 2018-05-14 04:42 UTC
Labels: duplicate
